# Generated by Django 4.0.3 on 2022-09-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.PositiveIntegerField(verbose_name='№')),
                ('order_number', models.BigIntegerField(verbose_name='заказ №')),
                ('price_dollar', models.BigIntegerField(verbose_name='стоимость,$')),
                ('price_ruble', models.BigIntegerField(verbose_name='стоимость,₽')),
                ('delivery_time', models.DateField(verbose_name='срок поставки')),
            ],
            options={
                'ordering': ['-added_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
