# Generated by Django 4.0.3 on 2022-09-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_alter_order_options_rename_number_order_row_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_row', models.PositiveIntegerField(default=2)),
                ('end_row', models.PositiveIntegerField(default=51)),
            ],
            options={
                'ordering': ['-added_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateField(blank=True, null=True, verbose_name='срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='заказ №'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_dollar',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_ruble',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='стоимость,₽'),
        ),
        migrations.AlterField(
            model_name='order',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№'),
        ),
    ]
