# Generated by Django 4.0.3 on 2022-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0004_order_number_alter_order_row_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='start_row',
        ),
        migrations.AddField(
            model_name='row',
            name='update_end_row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='row',
            name='end_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
