# Generated by Django 4.0.3 on 2022-09-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0005_remove_row_start_row_row_update_end_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='row_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
