# Generated by Django 4.0.3 on 2022-09-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0006_row_row_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заказ №'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_ruble',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='стоимость,₽'),
        ),
    ]
