# Generated by Django 4.0.3 on 2022-09-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0007_alter_order_order_number_alter_order_price_dollar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency_code', models.CharField(max_length=4)),
                ('currency_val_in_ruble', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['-added_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
